
package proxy;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "ReleveWS", targetNamespace = "http://AppReleveWS/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ReleveWS {


    /**
     * 
     * @return
     *     returns proxy.Releve
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getReleve", targetNamespace = "http://AppReleveWS/", className = "proxy.GetReleve")
    @ResponseWrapper(localName = "getReleveResponse", targetNamespace = "http://AppReleveWS/", className = "proxy.GetReleveResponse")
    @Action(input = "http://AppReleveWS/ReleveWS/getReleveRequest", output = "http://AppReleveWS/ReleveWS/getReleveResponse")
    public Releve getReleve();

    /**
     * 
     * @return
     *     returns java.util.List<proxy.Operation>
     */
    @WebMethod(operationName = "ListOperations")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ListOperations", targetNamespace = "http://AppReleveWS/", className = "proxy.ListOperations")
    @ResponseWrapper(localName = "ListOperationsResponse", targetNamespace = "http://AppReleveWS/", className = "proxy.ListOperationsResponse")
    @Action(input = "http://AppReleveWS/ReleveWS/ListOperationsRequest", output = "http://AppReleveWS/ReleveWS/ListOperationsResponse")
    public List<Operation> listOperations();

}
